name: flutter_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0  # Ya existente
  http: ^1.2.2  # Ya existente
  cupertino_icons: ^1.0.6  # Ya existente
  speech_to_text: ^7.0.0        # Reconocimiento de voz
  permission_handler: ^10.0.0  # Ya existente

  # Nuevas dependencias que necesitas agregar
  google_generative_ai: ^0.1.0   # Para Google Generative AI
  flutter_tts: ^3.5.0            # Para Text-To-Speech (TTS)
  intl: ^0.18.0                  # Para formateo de fechas
  connectivity_plus: ^3.0.3       # Para la conectividad de la red
  shared_preferences: ^2.1.1      # Para almacenamiento local

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
